### ISSUE TITLE
LIST: User 'quick views' items from list in tooltips

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/impactoss-client#27]
_From @joshmcarthur on August 8, 2016 20:42_

As a user

I want to quickly see a summary of the actions associated with a recommendation from the list page

So that I don't have to jump into each recommendation page to see the actions.

---

Development tasks:
1. Implement action list bound to the action count label on the recommendations list page
2.  Ensure hover is friendly - e.g. don't just bind the hiding of the box when the cursor leaves the icon, allow the user to scroll over the action list.
3. UI implemented as per wireframes

![screenshot 2016-08-09 08 44 00](https://cloud.githubusercontent.com/assets/292020/17495557/98994abc-5e0d-11e6-9eb0-6c2625f61770.png)

_Copied from original issue: dumparkltd/hr-nmrf-server#34_

**Comment by dmprk** [comment]
![tooltip.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46fc9b952f968ab9cda5fd53b652fa912a5265296b51fb7272dde62ebb1b2b58575e4fff42585f12fbaa8028afa42062c80d55b98e30063e937f03a6aa811eb500bf208b4683b5b98a45c6eb3c37aa.png)
